name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.10'
          - '5.12'
          - '5.14'
          - '5.20'
          - '5.30'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -n --installdeps .
          cpanm TAP::Harness::Archive
      - name: Run Tests
        run: |
          mkdir results
          prove -l -a results/tap.tgz t t/mojo t/mojolicious
          cd results; tar -zvxf tap.tgz; rm tap.tgz; cd ..
      - uses: actions/upload-artifact@v2
        with:
          name: TAP
          path: results/
