name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.30'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -n --installdeps .
          cpanm -n Sub::Util IO::Socket::IP
          cpanm -n Cpanel::JSON::XS EV IO::Socket::SSL IO::Socket::Socks
          cpanm -n Role::Tiny Test::Pod Test::Pod::Coverage
      - name: Run Tests
        run: prove -l t t/mojo t/mojolicious
        env:
          TEST_POD: 1
          TEST_TLS: 1
          TEST_SOCKS: 1
          TEST_UNIX: 1
          TEST_EV: 1
